import { SeminarContentScene, BMBKnowledgeBaseItem } from "../db/schema";

export const VERIFIED_BMB_KNOWLEDGE_BASE: Omit<BMBKnowledgeBaseItem, "updated_at">[] = [
  {
    id: "kb-001",
    category: "general_info",
    title: "BMB Educom Mission",
    content: "BMB Educom is a premier skill-enablement educational institute focused on practical, high-impact digital technology training, AI empowerment, and career-oriented skill development.",
    verified: true,
    active: true,
    updated_by: "System Administrator"
  },
  {
    id: "kb-002",
    category: "rules",
    title: "Friday Seminar Schedule & Format",
    content: "BMB Educom AI Seminar is conducted every Friday from 11:00 AM to 4:00 PM IST. The seminar includes a cinematic Hindi documentary experience followed by an official 4-question server-timed quiz (120 seconds) and live ranking leaderboard.",
    verified: true,
    active: true,
    updated_by: "System Administrator"
  },
  {
    id: "kb-003",
    category: "practical_labs",
    title: "Hands-on Practical Methodology",
    content: "Training emphasizes building real-world projects, utilizing modern AI tools (LLMs, Diffusion models, Agentic frameworks), portfolio creation, and client project simulations rather than purely theoretical lectures.",
    verified: true,
    active: true,
    updated_by: "System Administrator"
  },
  {
    id: "kb-004",
    category: "mentorship",
    title: "Career & Skill Guidance Policy",
    content: "BMB Educom provides industry mentorship, portfolio reviews, and freelance market readiness. Earning and career outcomes are dependent on individual dedication, verified skills, portfolio quality, and client acquisition consistency. BMB Educom never promises unrealistic or guaranteed income.",
    verified: true,
    active: true,
    updated_by: "System Administrator"
  },
  {
    id: "kb-005",
    category: "certifications",
    title: "Verified Skill Certification",
    content: "Students and attendees who successfully complete the hands-on tracks and evaluation milestones receive verified performance certificates validating their competency in AI-assisted workflows.",
    verified: true,
    active: true,
    updated_by: "System Administrator"
  }
];

export const SEMINAR_27_SCENES_SEED: Omit<SeminarContentScene, "id">[] = [
  {
    scene_number: 1,
    title: "1. AI क्या है? (What is Artificial Intelligence?)",
    narration_script_hi: "नमस्ते और BMB Educom के विशेष AI सेमिनार में आपका स्वागत है। आर्टिफिशियल इंटेलिजेंस यानी AI, कंप्यूटर विज्ञान की वह शाखा है जो मशीनों को सोचने, समझने, सीखने और निर्णय लेने की मानवीय क्षमता प्रदान करती है। यह सिर्फ एक सॉफ्टवेयर नहीं, बल्कि बुद्धिमत्ता की नई डिजिटल क्रांति है।",
    captions_hi: "AI कंप्यूटर विज्ञान की वह अत्याधुनिक शाखा है जो मशीनों में मानवीय बुद्धिमत्ता और निर्णय क्षमता विकसित करती है।",
    key_takeaways: ["बुद्धिमत्ता का डिजिटल विकास", "समस्या समाधान और तार्किक निर्णय", "स्वचालित कार्यप्रणाली"],
    animation_type: "neural_network",
    visual_description: "Futuristic 3D crystalline neural brain pulsing with golden synaptic energy pulses in a dark cinematic space",
    duration_seconds: 24,
    display_order: 1,
    active: true
  },
  {
    scene_number: 2,
    title: "2. AI कैसे काम करता है? (How AI Works)",
    narration_script_hi: "AI का मूल आधार डेटा है। जब हम किसी कंप्यूटर मॉडल को लाखों-करोड़ों उदाहरण, चित्र या टेक्स्ट दिखाते हैं, तो वह एल्गोरिदम के माध्यम से उनमें छिपे पैटर्न्स को पहचानता है। इसी सीखे हुए ज्ञान के आधार पर वह नए और अनदेखे सवालों के सटीक उत्तर देता है।",
    captions_hi: "AI बड़े पैमाने पर डेटा से पैटर्न्स सीखता है और गणितीय एल्गोरिदम के जरिए सटीक भविष्यवाणी करता है।",
    key_takeaways: ["डेटा इनपुट और प्रोसेसिंग", "पैटर्न रिकॉग्निशन", "भविष्यवाणी और निर्णय"],
    animation_type: "neural_network",
    visual_description: "Streams of glowing data nodes converging into a central holographic processing core with dynamic energy waves",
    duration_seconds: 22,
    display_order: 2,
    active: true
  },
  {
    scene_number: 3,
    title: "3. Types of AI (Narrow, General & Super)",
    narration_script_hi: "AI को मुख्य रूप से तीन श्रेणियों में बांटा जाता है: नैरो AI, जो किसी एक विशेष काम में माहिर होता है जैसे फेस लॉक; जनरल AI, जो इंसान की तरह हर क्षेत्र में सोच सके; और सुपर AI, जो मानव बौद्धिक क्षमता से भी आगे की कल्पना है। आज हम मुख्य रूप से नैरो और एडवांस्ड AI का उपयोग कर रहे हैं।",
    captions_hi: "तीन मुख्य प्रकार: Artificial Narrow AI (ANI), Artificial General AI (AGI), और Artificial Super AI (ASI)।",
    key_takeaways: ["Narrow AI: विशिष्ट कार्य विशेषज्ञ", "General AI: मानव-समान बुद्धिमत्ता", "Super AI: भविष्य की उच्चतम परिकल्पना"],
    animation_type: "agent_flow",
    visual_description: "3 holographic glass pillars representing Narrow, General, and Super AI with evolving energy rings",
    duration_seconds: 26,
    display_order: 3,
    active: true
  },
  {
    scene_number: 4,
    title: "4. Machine Learning (मशीन लर्निंग)",
    narration_script_hi: "मशीन लर्निंग, AI का वह दिल है जहां सिस्टम को बिना सीधे कोड लिखे, डेटा से खुद सीखने की क्षमता दी जाती है। इसमें सुपरवाइज्ड, अनसुपरवाइज्ड और रीइन्फोर्समेंट लर्निंग जैसी तकनीकें शामिल हैं जो अनुभव के साथ मॉडल को और अधिक सटीक बनाती हैं।",
    captions_hi: "मशीन लर्निंग डेटा और अनुभवों से स्वचालित रूप से सीखने और स्वयं को बेहतर बनाने की वैज्ञानिक पद्धति है।",
    key_takeaways: ["Supervised: लेबल डेटा से सीखना", "Unsupervised: छिपे पैटर्न्स खोजना", "Reinforcement: रिवॉर्ड आधारित सुधार"],
    animation_type: "neural_network",
    visual_description: "Multi-layered dynamic algorithmic decision tree evolving in 3D glowing neon cyan and amber matrices",
    duration_seconds: 25,
    display_order: 4,
    active: true
  },
  {
    scene_number: 5,
    title: "5. Deep Learning & Neural Networks",
    narration_script_hi: "डीप लर्निंग मानव मस्तिष्क के न्यूरॉन्स से प्रेरित आर्टिफिशियल न्यूरल नेटवर्क्स पर आधारित है। इसमें कई गहरी परतें होती हैं जो जटिल से जटिल इमेजेस, आवाज और भाषा को बहुत गहराई से समझकर सटीक निष्कर्ष निकालती हैं।",
    captions_hi: "डीप लर्निंग मानव दिमाग के न्यूरॉन्स की तरह बहुस्तरीय आर्टिफिशियल न्यूरल नेटवर्क्स पर काम करती है।",
    key_takeaways: ["आर्टिफिशियल न्यूरॉन्स", "मल्टी-लेयर आर्किटेक्चर", "जटिल डेटा विश्लेषण"],
    animation_type: "neural_network",
    visual_description: "Interconnected multi-layered glowing neural network with pulses cascading across deep hidden layers",
    duration_seconds: 24,
    display_order: 5,
    active: true
  },
  {
    scene_number: 6,
    title: "6. Generative AI (जेनरेटिव एआई)",
    narration_script_hi: "जेनरेटिव AI केवल विश्लेषण नहीं करता, बल्कि पूरी तरह से नया और मौलिक कंटेंट बनाता है। चाहे वह रचनात्मक लेख हो, हाई-क्वालिटी फोटो हो, संगीत हो या सॉफ्टवेयर कोड—जेनरेटिव AI रचनात्मकता के नए द्वार खोल रहा है।",
    captions_hi: "Generative AI नए टेक्स्ट, फोटो, वीडियो, म्यूजिक और सॉफ्टवेयर कोड को सेकंडों में सृजित करने की शक्ति देता है।",
    key_takeaways: ["मौलिक कंटेंट सृजन", "लार्ज लैंग्वेज मॉडल्स (LLMs)", "डिफ्यूजन विजुअल टेक्नोलॉजी"],
    animation_type: "creative_studio",
    visual_description: "A digital canvas where glowing text prompt morphs into a photorealistic 3D environment in real-time",
    duration_seconds: 24,
    display_order: 6,
    active: true
  },
  {
    scene_number: 7,
    title: "7. Computer Vision (कंप्यूटर विजन)",
    narration_script_hi: "कंप्यूटर विजन मशीनों को देखने और दृश्यों को समझने की आंखें देता है। यह मेडिकल स्कैन में बीमारियों की पहचान, ट्रैफिक मॉनिटरिंग, सिक्योरिटी और ऑटोनॉमस कारों के लिए रीढ़ की हड्डी साबित हो रहा है।",
    captions_hi: "कंप्यूटर विजन इमेजेस और वीडियो से वस्तुओं, चेहरों और गतिविधियों को पहचानने की तकनीक है।",
    key_takeaways: ["ऑब्जेक्ट डिटेक्शन", "मेडिकल इमेज डायग्नोस्टिक्स", "सेल्फ-ड्राइविंग विजन"],
    animation_type: "robotics_lab",
    visual_description: "Futuristic HUD scanning realistic city footage with precise 3D bounding boxes and analytical telemetry",
    duration_seconds: 23,
    display_order: 7,
    active: true
  },
  {
    scene_number: 8,
    title: "8. Natural Language Processing (NLP)",
    narration_script_hi: "NLP की मदद से कंप्यूटर इंसानी भाषा के व्याकरण, अर्थ और भावनाओं को समझता है। यह भाषा अनुवाद, वॉइस सर्च, सारांश और टेक्स्ट एनालिसिस को सहज और स्वाभाविक बनाता है।",
    captions_hi: "Natural Language Processing मशीनों को मानवीय भाषा को धाराप्रवाह समझने और बोलने में सक्षम बनाती है।",
    key_takeaways: ["भाषा की गहरी समझ", "रियल-टाइम बहुभाषी अनुवाद", "भावना और संदर्भ विश्लेषण"],
    animation_type: "agent_flow",
    visual_description: "Floating Hindi and English typography interacting with glowing token vectors and semantic relationships",
    duration_seconds: 22,
    display_order: 8,
    active: true
  },
  {
    scene_number: 9,
    title: "9. Conversational AI & Chatbots",
    narration_script_hi: "कन्वर्सेशनल AI चैटबॉट्स और वॉइस एजेंट्स को इंसानों जैसी स्वाभाविक बातचीत करने की ताकत देता है। 24 घंटे कस्टमर सपोर्ट, तत्काल जानकारी और समस्याओं का समाधान अब पलक झपकते संभव है।",
    captions_hi: "Conversational AI 24x7 तत्काल प्रतिक्रिया और इंसानों जैसी स्वाभाविक बातचीत उपलब्ध कराता है।",
    key_takeaways: ["24/7 तत्काल सहायता", "पर्सनलाइज्ड यूजर एक्सपीरियंस", "मल्टी-चैनल एकीकरण"],
    animation_type: "agent_flow",
    visual_description: "Sleek conversational holographic interface exchanging fast, helpful queries and smart cards",
    duration_seconds: 21,
    display_order: 9,
    active: true
  },
  {
    scene_number: 10,
    title: "10. AI Agents (स्वायत्त एआई एजेंट्स)",
    narration_script_hi: "AI एजेंट्स पारंपरिक बॉट्स से कई कदम आगे हैं। ये केवल जवाब नहीं देते, बल्कि आपके दिए गए लक्ष्य को हासिल करने के लिए खुद योजना बनाते हैं, टूल्स का उपयोग करते हैं और जटिल कार्यों को बिना किसी हस्तक्षेप के पूरा करते हैं।",
    captions_hi: "AI Agents स्वायत्त निर्णय लेकर लक्ष्य निर्धारण, टूल यूसेज और जटिल टास्क पूरा करने में सक्षम हैं।",
    key_takeaways: ["स्वायत्त टास्क एक्जीक्यूशन", "टूल एवं API कॉलिंग", "मल्टी-एजेंट वर्कफ्लो"],
    animation_type: "agent_flow",
    visual_description: "Network of autonomous AI agent spheres collaborating in parallel to solve complex multi-stage tasks",
    duration_seconds: 25,
    display_order: 10,
    active: true
  },
  {
    scene_number: 11,
    title: "11. Robotics & Intelligent Machines",
    narration_script_hi: "जब AI को भौतिक रोबोट्स के साथ जोड़ा जाता है, तो वे वेयरहाउस मैनेजमेंट, जटिल सर्जरी, आपदा प्रबंधन और आधुनिक मैन्युफैक्चरिंग में इंसानों की सुरक्षा और दक्षता को नई ऊंचाइयों पर ले जाते हैं।",
    captions_hi: "रोबोटिक्स और AI का मिलन उद्योगों, सर्जरी और सुरक्षा में बेजोड़ सटीकता प्रदान करता है।",
    key_takeaways: ["स्मार्ट मैन्युफैक्चरिंग", "सटीक मेडिकल सर्जरी", "खतरनाक कार्यों में सुरक्षा"],
    animation_type: "robotics_lab",
    visual_description: "High-precision robotic arm calibrating a microchip under volumetric laboratory spotlight",
    duration_seconds: 23,
    display_order: 11,
    active: true
  },
  {
    scene_number: 12,
    title: "12. AI in Graphic Design (ग्राफिक डिजाइन)",
    narration_script_hi: "ग्राफिक डिजाइन में AI टूल्स डिजाइनर्स की कल्पना को कुछ ही सेकंडों में डिजिटल कैनवास पर उतार देते हैं। पोस्टर डिजाइन, लोगो कॉन्सेप्ट, बैकग्राउंड जेनरेशन और कलर पैलेट क्रिएशन अब पहले से 10 गुना तेज हो चुके हैं।",
    captions_hi: "AI टूल्स डिजाइनर्स को अभूतपूर्व स्पीड, क्रिएटिविटी और विजुअल एसेट्स जेनरेशन की क्षमता प्रदान करते हैं।",
    key_takeaways: ["फास्ट कॉन्सेप्ट डिजाइन", "स्मार्ट लेआउट जनरेशन", "वेक्टर एवं 3D विजुअल्स"],
    animation_type: "creative_studio",
    visual_description: "Digital graphic studio where vector illustrations and 3D branding packages generate interactively",
    duration_seconds: 24,
    display_order: 12,
    active: true
  },
  {
    scene_number: 13,
    title: "13. AI in Video Editing (वीडियो एडिटिंग)",
    narration_script_hi: "वीडियो एडिटिंग में घंटों का उबाऊ काम अब सेकंडों में हो रहा है। ऑटोमैटिक सबटाइटल्स, सीन रिमूवल, बी-रोल जेनरेशन और कलर ग्रेडिंग जैसे टूल्स से एक अकेला क्रिएटर भी स्टूडियो-लेवल वीडियो बना सकता है।",
    captions_hi: "AI वीडियो टूल्स ऑटोमैटिक कटिंग, ट्रांसक्रिप्शन, कलर करेक्शन और VFX को बेहद आसान बनाते हैं।",
    key_takeaways: ["ऑटो सबटाइटलिंग एवं सिंक", "स्मार्ट सीन डिटेक्शन", "स्टूडियो क्वालिटी पोस्ट-प्रोडक्शन"],
    animation_type: "creative_studio",
    visual_description: "Timeline interface with AI waveform scrubbing, instant B-roll generation, and auto-captions",
    duration_seconds: 23,
    display_order: 13,
    active: true
  },
  {
    scene_number: 14,
    title: "14. AI in Animation (2D & 3D एनिमेशन)",
    narration_script_hi: "एनिमेशन इंडस्ट्री में AI कैरेक्टर डिजाइन, फ्रेम-बाय-फ्रेम इन-बिटवीनिंग और रीयल-टाइम मोशन कैप्चर में क्रांति ला रहा है। अब छोटे स्टूडियो और व्यक्तिगत एनिमेटर्स भी वर्ल्ड-क्लास स्टोरीज तैयार कर सकते हैं।",
    captions_hi: "AI एनिमेशन मोशन कैप्चर, कैरेक्टर रिगिंग और फ्रेम जनरेशन को ऑटोमेट करके प्रोडक्शन तेज करता है।",
    key_takeaways: ["कैरेक्टर इन-बिटवीनिंग", "रीयल-टाइम मोशन कैप्चर", "कम लागत में हाई-एंड एनिमेशन"],
    animation_type: "creative_studio",
    visual_description: "3D stylized character executing fluid parkour movements with real-time motion vector overlays",
    duration_seconds: 24,
    display_order: 14,
    active: true
  },
  {
    scene_number: 15,
    title: "15. AI in Coding (सॉफ्टवेयर कोडिंग)",
    narration_script_hi: "कोडिंग में AI डेवलपर का सबसे भरोसेमंद साथी बन चुका है। कोड सुझाव, एरर डिबगिंग, आर्किटेक्चर प्लानिंग और ऑटोमेटेड टेस्टिंग से सॉफ्टवेयर डेवलपमेंट की गति कई गुना बढ़ जाती है।",
    captions_hi: "AI कोडिंग असिस्टेंट्स कोड जनरेशन, बग फिक्सिंग और टेस्टिंग को तेज और सुरक्षित बनाते हैं।",
    key_takeaways: ["इंटेलिजेंट कोड कम्पलीशन", "त्वरित बग आइडेंटिफिकेशन", "मॉडर्न फ्रेमवर्क एकीकरण"],
    animation_type: "code_matrix",
    visual_description: "Glowing code editor typing clean TypeScript and Python code with instant AI inline completions",
    duration_seconds: 23,
    display_order: 15,
    active: true
  },
  {
    scene_number: 16,
    title: "16. AI in Business (बिजनेस में एआई)",
    narration_script_hi: "बिजनेस में डेटा-आधारित फैसले ही सफलता तय करते हैं। AI इन्वेंटरी प्रेडिक्शन, फाइनेंशियल फोरकास्टिंग और ऑपरेशनल एफिशिएंसी को ट्रैक करके कंपनियों को नुकसान से बचाता है और मुनाफा बढ़ाता है।",
    captions_hi: "बिजनेस में AI प्रेडिक्टिव एनालिटिक्स, लागत नियंत्रण और रणनीतिक निर्णय क्षमता को सशक्त करता है।",
    key_takeaways: ["डेटा आधारित निर्णय", "इन्वेंटरी और सप्लाई चेन मैनेजमेंट", "कॉस्ट ऑप्टिमाइजेशन"],
    animation_type: "bmb_hub",
    visual_description: "Interactive corporate dashboard displaying predictive trend charts and enterprise resource telemetry",
    duration_seconds: 24,
    display_order: 16,
    active: true
  },
  {
    scene_number: 17,
    title: "17. AI in Marketing (डिजिटल मार्केटिंग)",
    narration_script_hi: "मार्केटिंग में AI ग्राहकों की रुचि को बारीकी से समझकर हाइपर-पर्सनलाइज्ड विज्ञापन और कंटेंट तैयार करता है। इससे सही समय पर सही ग्राहक तक पहुंचकर बिजनेस का आरओआई अधिकतम होता है।",
    captions_hi: "AI मार्केटिंग सटीक ऑडियंस टारगेटिंग, ए/बी टेस्टिंग और कन्वर्जन रेट को कई गुना बढ़ाती है।",
    key_takeaways: ["हाइपर-पर्सनलाइज्ड कैंपेन", "ऑडियंस बिहेवियर इनसाइट्स", "उच्च विज्ञापन रिटर्न (ROI)"],
    animation_type: "agent_flow",
    visual_description: "Dynamic funnel visualization tracking user engagement heatmaps and automated ad variants",
    duration_seconds: 23,
    display_order: 17,
    active: true
  },
  {
    scene_number: 18,
    title: "18. AI in Education (शिक्षा में क्रांति)",
    narration_script_hi: "शिक्षा में AI हर विद्यार्थी के लिए एक निजी ट्यूटर बन सकता है। जो छात्र जिस विषय में कमजोर है, AI उसे उसी की गति और शैली में आसान उदाहरणों के साथ समझाकर सशक्त बनाता है।",
    captions_hi: "AI शिक्षा हर छात्र की व्यक्तिगत गति और आवश्यकता के अनुसार पर्सनलाइज्ड लर्निंग अनुभव देती है।",
    key_takeaways: ["पर्सनलाइज्ड स्टडी प्लान", "24x7 डाउट सॉल्विंग", "समावेशी शिक्षा पद्धति"],
    animation_type: "bmb_hub",
    visual_description: "Digital classroom with adaptive learning modules tailoring lessons to individual student graphs",
    duration_seconds: 22,
    display_order: 18,
    active: true
  },
  {
    scene_number: 19,
    title: "19. AI in Healthcare (स्वास्थ्य सेवा)",
    narration_script_hi: "हेल्थकेयर में AI जीवन रक्षक साबित हो रहा है। कैंसर जैसी गंभीर बीमारियों की शुरुआती पहचान, नई दवाओं का तेजी से विकास और टेलीमेडिसिन के जरिए दूरदराज के इलाकों तक विशेषज्ञ सलाह पहुंचाई जा रही है।",
    captions_hi: "हेल्थकेयर में AI शुरुआती बीमारी पहचान, ड्रग डिस्कवरी और सटीक इलाज में मदद कर जीवन बचाता है।",
    key_takeaways: ["अर्ली स्टेज डायग्नोस्टिक्स", "दवा खोज में गति", "रिमोट पेशेंट मॉनिटरिंग"],
    animation_type: "robotics_lab",
    visual_description: "3D holographic medical scan analyzing cellular structures with high-confidence predictive markers",
    duration_seconds: 24,
    display_order: 19,
    active: true
  },
  {
    scene_number: 20,
    title: "20. AI in Sales & CRM (सेल्स और लीड्स)",
    narration_script_hi: "सेल्स में AI लीड्स की गंभीरता को स्कोर करता है, फॉलो-अप ईमेल्स ऑटोमेट करता है और कस्टमर जर्नी को ट्रैक करता है। इससे सेल्स टीम का समय बचता है और कन्वर्जन रेट में भारी उछाल आता है।",
    captions_hi: "AI सेल्स में लीड स्कोरिंग, ऑटोमेटेड फॉलो-अप और डील क्लोजिंग को सुपरचार्ज करता है।",
    key_takeaways: ["इंटेलिजेंट लीड स्कोरिंग", "स्मार्ट फॉलो-अप वर्कफ्लो", "उच्च क्लोजिंग रेशियो"],
    animation_type: "bmb_hub",
    visual_description: "Dynamic CRM pipeline moving prospects smoothly from discovery to confirmed conversions",
    duration_seconds: 23,
    display_order: 20,
    active: true
  },
  {
    scene_number: 21,
    title: "21. AI Automation & RPA (ऑटोमेशन)",
    narration_script_hi: "रोबोटिक प्रोसेस ऑटोमेशन यानी RPA, डेटा एंट्री, इनवॉइस प्रोसेसिंग और रिपोर्ट्स तैयार करने जैसे दोहराए जाने वाले कामों को इंसानों से कहीं तेजी से और बिना किसी गलती के पूरा करता है।",
    captions_hi: "AI ऑटोमेशन रोजमर्रा के मैनुअल और जटिल डाटा कार्यों को शून्य त्रुटि के साथ ऑटोमेट करता है।",
    key_takeaways: ["मैनुअल गलतियों का खात्मा", "24x7 निरंतर संचालन", "सटीक डेटा सिंक्रोनाइजेशन"],
    animation_type: "code_matrix",
    visual_description: "Automated data flow bridging legacy databases, spreadsheet rows, and cloud endpoints seamlessly",
    duration_seconds: 23,
    display_order: 21,
    active: true
  },
  {
    scene_number: 22,
    title: "22. Future of AI (एआई का भविष्य)",
    narration_script_hi: "भविष्य में AI, क्वांटम कंप्यूटिंग और बायो-टेक्नोलॉजी का संगम जलवायु परिवर्तन से लड़ने, अंतरिक्ष अन्वेषण और ऊर्जा संकट को हल करने में मानव सभ्यता को सबसे बड़ी छलांग देगा।",
    captions_hi: "AI का भविष्य क्वांटम कंप्यूटिंग, स्वच्छ ऊर्जा और वैश्विक चुनौतियों के समाधान से जुड़ा है।",
    key_takeaways: ["क्वांटम AI एकीकरण", "पर्यावरण और ऊर्जा समाधान", "जिम्मेदार और सुरक्षित AI"],
    animation_type: "neural_network",
    visual_description: "Cinematic cosmic vista showing quantum orbits interfacing with planetary earth climate models",
    duration_seconds: 25,
    display_order: 22,
    active: true
  },
  {
    scene_number: 23,
    title: "23. AI Careers & Job Roles (करियर के अवसर)",
    narration_script_hi: "AI सिर्फ पुरानी नौकरियों को नहीं बदल रहा, बल्कि लाखों नए करियर विकल्प बना रहा है—जैसे AI प्रॉम्प्ट इंजीनियर, मशीन लर्निंग स्पेशलिस्ट, AI कंटेंट स्ट्रैटेजिस्ट और ऑटोमेशन कंसल्टेंट।",
    captions_hi: "AI इंडस्ट्री में प्रॉम्प्ट इंजीनियरिंग, ऑटोमेशन कंसल्टिंग और AI मैनेजमेंट के नए करियर बन रहे हैं।",
    key_takeaways: ["AI प्रॉम्प्ट इंजीनियर", "ऑटोमेशन आर्किटेक्ट", "AI कंटेंट और विजुअल स्पेशलिस्ट"],
    animation_type: "career_path",
    visual_description: "Career tree branching into high-demand AI professional disciplines with salary & growth trajectories",
    duration_seconds: 25,
    display_order: 23,
    active: true
  },
  {
    scene_number: 24,
    title: "24. Freelancing Opportunities (फ्रीलांसिंग)",
    narration_script_hi: "इंटरनेट के दौर में आप घर बैठे ग्लोबल क्लाइंट्स के लिए काम कर सकते हैं। AI टूल्स की मदद से डिजाइन, वीडियो, कोडिंग और कंटेंट प्रोजेक्ट्स को कम समय में पूरा करके अपनी फ्रीलांसिंग आय को तेजी से बढ़ाया जा सकता है।",
    captions_hi: "AI स्किल्स के साथ आप Upwork, Fiverr और डायरेक्ट क्लाइंट्स को प्रीमियम सेवाएं दे सकते हैं।",
    key_takeaways: ["ग्लोबल क्लाइंट रीच", "हाई-क्वालिटी डिलीवरी स्पीड", "पोर्टफोलियो आधारित ग्रोथ"],
    animation_type: "career_path",
    visual_description: "World map connecting a dedicated Indian creator to global remote clients with transparent project streams",
    duration_seconds: 25,
    display_order: 24,
    active: true
  },
  {
    scene_number: 25,
    title: "25. Skill Development & Practical Roadmap",
    narration_script_hi: "याद रखें, किसी भी टूल से ज्यादा महत्वपूर्ण आपका अपना कौशल और निरंतर अभ्यास है। जब आप बेसिक्स मजबूत करते हैं और 3 से 5 लाइव प्रोजेक्ट्स का मजबूत पोर्टफोलियो बनाते हैं, तो अवसर खुद आपके पास आते हैं।",
    captions_hi: "सच्ची सफलता टूल्स की समझ, लाइव प्रोजेक्ट्स और एक शानदार पोर्टफोलियो से हासिल होती है।",
    key_takeaways: ["प्रैक्टिकल प्रोजेक्ट्स", "मजबूत डिजिटल पोर्टफोलियो", "सच्ची लगन और निरंतरता"],
    animation_type: "career_path",
    visual_description: "Step-by-step illuminated milestone staircase leading to a verified industry portfolio showcase",
    duration_seconds: 24,
    display_order: 25,
    active: true
  },
  {
    scene_number: 26,
    title: "26. BMB Educom Learning Journey (बीएमबी यात्रा)",
    narration_script_hi: "BMB Educom इसी प्रैक्टिकल विजन के साथ आपके साथ खड़ा है। हमारे अनुभवी मेंटर्स, आधुनिक कंप्यूटर लैब्स और प्रोजेक्ट-आधारित ट्रेनिंग आपको सिर्फ थ्योरी नहीं, बल्कि इंडस्ट्री के लिए पूरी तरह तैयार करते हैं।",
    captions_hi: "BMB Educom देता है हैंड्स-ऑन प्रोजेक्ट ट्रेनिंग, अनुभवी मेंटरशिप और करियर सपोर्ट।",
    key_takeaways: ["हैंड्स-ऑन मेंटरशिप", "इंडस्ट्री-ओरिएंटेड लैब्स", "सत्यापित स्किल सर्टिफिकेशन"],
    animation_type: "bmb_hub",
    visual_description: "State of the art BMB Educom learning hub with students collaborating on real-world projects",
    duration_seconds: 26,
    display_order: 26,
    active: true
  },
  {
    scene_number: 27,
    title: "27. Friday Seminar Live Invitation & Quiz Challenge",
    narration_script_hi: "अब समय है अपने ज्ञान को परखने का! आगे 4 प्रश्नों का आधिकारिक AI क्विज शुरू होने वाला है। आपके पास होंगे ठीक 2 मिनट यानी 120 सेकंड। सही और तेज उत्तर देकर आप आज के शुक्रवार के लीडरबोर्ड पर टॉप रैंक हासिल कर सकते हैं। ऑल द बेस्ट!",
    captions_hi: "तैयार हो जाइए! 4 प्रश्नों का लाइव AI क्विज शुरू होने वाला है। समय: 2 मिनट (120 सेकंड)। ऑल द बेस्ट!",
    key_takeaways: ["4 महत्वपूर्ण प्रश्न", "2 मिनट का सर्वर टाइमर", "लाइव सेमिनार लीडरबोर्ड रैंकिंग"],
    animation_type: "bmb_hub",
    visual_description: "Grand golden cinematic emblem transitioning to a high-tech glowing countdown quiz arena gate",
    duration_seconds: 26,
    display_order: 27,
    active: true
  }
];
