import { QuestionBankItem } from "../db/schema";

export const SEED_QUESTION_BANK: Omit<QuestionBankItem, "created_at">[] = [
  // 1-15: AI Fundamentals & Core Concepts
  {
    id: "q-001",
    question: "AI का पूरा नाम (Full Form) क्या है?",
    options: ["Artificial Intelligence", "Automated Information", "Advanced Internet", "Audio Interactive"],
    correct_option: 0,
    category: "AI Basics",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-002",
    question: "आर्टिफिशियल इंटेलिजेंस (AI) का मुख्य उद्देश्य क्या है?",
    options: ["मानव जैसी बुद्धिमत्ता और निर्णय क्षमता मशीनों में विकसित करना", "कंप्यूटर की स्क्रीन को बड़ा करना", "केवल इंटरनेट की स्पीड बढ़ाना", "प्रिंटर से रंगीन प्रिंट निकालना"],
    correct_option: 0,
    category: "AI Basics",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-003",
    question: "मशीन लर्निंग (Machine Learning) का मूल सिद्धांत क्या है?",
    options: ["डेटा और अनुभवों से बिना प्रत्यक्ष प्रोग्रामिंग के सीखना", "हार्डवेयर के पुर्जों को बदलना", "सिर्फ गणित के सूत्र रटना", "वेबसाइट को हैक करना"],
    correct_option: 0,
    category: "Machine Learning",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-004",
    question: "डीप लर्निंग (Deep Learning) किस पर आधारित है?",
    options: ["आर्टिफिशियल न्यूरल नेटवर्क्स (Artificial Neural Networks)", "माइक्रोसॉफ्ट एक्सेल शीट्स", "कंप्यूटर के SMPS", "सीडी-रोम ड्राइव"],
    correct_option: 0,
    category: "Deep Learning",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-005",
    question: "Generative AI का प्रमुख कार्य क्या है?",
    options: ["नया टेक्स्ट, इमेज, ऑडियो या कोड जनरेट करना", "हार्ड डिस्क को फॉर्मेट करना", "कंप्यूटर का तापमान कम करना", "बिजली का बिल बचाना"],
    correct_option: 0,
    category: "Generative AI",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-006",
    question: "कंप्यूटर विजन (Computer Vision) तकनीक का क्या काम है?",
    options: ["इमेजेस और वीडियोज को समझना और पहचानना", "कंप्यूटर का चश्मा साफ करना", "साउंड कार्ड का वॉल्यूम बढ़ाना", "कीबोर्ड की टाइपिंग स्पीड नापना"],
    correct_option: 0,
    category: "Computer Vision",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-007",
    question: "NLP (Natural Language Processing) का मुख्य उपयोग क्या है?",
    options: ["मानव भाषा (हिंदी/अंग्रेजी आदि) को समझना और प्रोसेस करना", "नेटवर्क के तारों को जोड़ना", "नया लैपटॉप असेंबल करना", "सिर्फ नंबरों को जोड़ना"],
    correct_option: 0,
    category: "NLP",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-008",
    question: "AI प्रॉम्प्ट (Prompt) क्या होता है?",
    options: ["AI मॉडल को दिया जाने वाला इनपुट या निर्देश", "कंप्यूटर का पासवर्ड", "एक प्रकार का एंटीवायरस", "प्रिंटर का एरर मैसेज"],
    correct_option: 0,
    category: "Generative AI",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-009",
    question: "LLM का फुल फॉर्म क्या है?",
    options: ["Large Language Model", "Low Level Machine", "Local Logic Memory", "Long Line Module"],
    correct_option: 0,
    category: "Generative AI",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-010",
    question: "ChatGPT और Gemini किस प्रकार के AI सिस्टम हैं?",
    options: ["कन्वर्सेशनल जेनरेटिव AI (Conversational GenAI)", "ऑपरेटिंग सिस्टम", "ग्राफिक्स कार्ड ड्राइवर", "डेटाबेस मैनेजमेंट सिस्टम"],
    correct_option: 0,
    category: "Conversational AI",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-011",
    question: "AI एजेंट्स (AI Agents) की सबसे बड़ी खासियत क्या है?",
    options: ["लक्ष्य आधारित स्वायत्त (Autonomous) कार्य और निर्णय लेना", "केवल गाने बजाना", "बिना इंटरनेट के कंप्यूटर बंद करना", "प्रिंटर में कागज डालना"],
    correct_option: 0,
    category: "AI Agents",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-012",
    question: "सुपरवाइज्ड लर्निंग (Supervised Learning) में मॉडल को कैसे ट्रेन किया जाता है?",
    options: ["लेबल किए गए डेटा (Labeled Data) और सही उत्तरों के साथ", "बिना किसी डेटा के", "केवल रैंडम नंबरों से", "सिर्फ कंप्यूटर बंद करके"],
    correct_option: 0,
    category: "Machine Learning",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-013",
    question: "अनसुपरवाइज्ड लर्निंग (Unsupervised Learning) का उपयोग किसमें होता है?",
    options: ["अनलेबल डेटा में पैटर्न और क्लस्टर खोजना", "केवल गेम खेलना", "सॉफ्टवेयर इंस्टॉल करना", "कंप्यूटर चालू करना"],
    correct_option: 0,
    category: "Machine Learning",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-014",
    question: "रीइन्फोर्समेंट लर्निंग (Reinforcement Learning) किस सिद्धांत पर कार्य करती है?",
    options: ["रिवॉर्ड (पुरस्कार) और पेनल्टी (सजा) आधारित फीडबैक लूप", "किताबों को स्कैन करना", "सीधे मेमोरी कॉपी करना", "मदरबोर्ड को गर्म करना"],
    correct_option: 0,
    category: "Machine Learning",
    difficulty: "hard",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-015",
    question: "Artificial Narrow AI (ANI) का क्या अर्थ है?",
    options: ["एक विशिष्ट (Specific) कार्य में माहिर AI जैसे फेस रिकॉग्निशन", "मनुष्य से हर क्षेत्र में अधिक बुद्धिमान AI", "चेतना से युक्त काल्पनिक AI", "एक पुराना रोबोट"],
    correct_option: 0,
    category: "AI Basics",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },

  // 16-30: AI Tools in Creative, Video, Design & Coding
  {
    id: "q-016",
    question: "ग्राफिक डिजाइन में AI टूल्स (जैसे Midjourney, Canva AI) का क्या फायदा है?",
    options: ["तेजी से हाई-क्वालिटी विजुअल्स और क्रिएटिव एसेट्स बनाना", "कंप्यूटर की रैम को बढ़ाना", "प्रिंटर के इंक का रंग बदलना", "सिर्फ फाइल्स डिलीट करना"],
    correct_option: 0,
    category: "AI in Design",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-017",
    question: "वीडियो एडिटिंग में AI का उपयोग किस काम में सबसे ज्यादा होता है?",
    options: ["ऑटो-कैप्शन, सीन कटिंग, बैकग्राउंड रिमूवल और कलर ग्रेडिंग", "कैमरा का लेंस बदलना", "सिर्फ वीडियो डिलीट करना", "टीवी की स्क्रीन ठीक करना"],
    correct_option: 0,
    category: "AI in Video Editing",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-018",
    question: "AI एनिमेशन टूल्स 2D और 3D में क्या क्रांति ला रहे हैं?",
    options: ["मोशन कैप्चर, कैरेक्टर रिगिंग और फ्रेम जनरेशन को ऑटोमेट करना", "कार्टून की ड्राइंग मिटाना", "सिर्फ स्क्रीन ब्राइटनेस बढ़ाना", "ऑडियो को म्यूट करना"],
    correct_option: 0,
    category: "AI in Animation",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-019",
    question: "सॉफ्टवेयर कोडिंग में AI असिस्टेंट (जैसे GitHub Copilot) का मुख्य लाभ क्या है?",
    options: ["कोड सुझाव, ऑटो-कम्प्लीशन, डिबगिंग और डेवलपमेंट स्पीड बढ़ाना", "बिना कंप्यूटर के प्रोग्राम रन करना", "कीबोर्ड के बटन दबाना", "इंटरनेट का बिल कम करना"],
    correct_option: 0,
    category: "AI in Coding",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-020",
    question: "AI द्वारा टेक्स्ट-टू-इमेज (Text-to-Image) मॉडल कैसे काम करते हैं?",
    options: ["टेक्स्ट विवरण को डिफ्यूजन प्रोसेस द्वारा फोटो में परिवर्तित करते हैं", "गूगल से सीधे फोटो चुराते हैं", "स्कैनर से प्रिंट निकालते हैं", "कैमरा से लाइव फोटो खींचते हैं"],
    correct_option: 0,
    category: "Generative AI",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-021",
    question: "AI वॉइस क्लोनिंग और स्पीच सिंथेसिस (TTS) क्या है?",
    options: ["टेक्स्ट को प्राकृतिक मानवीय आवाज में बदलना", "माइक्रोफोन को रिपेयर करना", "गाना डाउनलोड करना", "रेडियो सिग्नल पकड़ना"],
    correct_option: 0,
    category: "Generative AI",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-022",
    question: "प्रॉम्प्ट इंजीनियरिंग (Prompt Engineering) क्या है?",
    options: ["AI मॉडल से सटीक परिणाम प्राप्त करने के लिए निर्देश डिजाइन करने की कला", "इंजीनियरिंग कॉलेज की डिग्री", "कंप्यूटर का पंखा ठीक करना", "इलेक्ट्रिक वायर जोड़ना"],
    correct_option: 0,
    category: "Prompt Engineering",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-023",
    question: "AI टूल्स का सही उपयोग करने पर एक क्रिएटर की उत्पादकता (Productivity) पर क्या असर पड़ता है?",
    options: ["काम की गति और गुणवत्ता दोनों में कई गुना वृद्धि होती है", "काम की गति धीमी हो जाती है", "क्रिएटिविटी पूरी तरह खत्म हो जाती है", "कोई प्रभाव नहीं पड़ता"],
    correct_option: 0,
    category: "AI Skills",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-024",
    question: "AI इनपेंटिंग (Inpainting) तकनीक का क्या अर्थ है?",
    options: ["इमेज के किसी चुनिंदा हिस्से को AI से हटाना या बदलना", "पूरी स्क्रीन को ब्लैक करना", "दीवार पर पेंट करना", "फोटो का साइज कम करना"],
    correct_option: 0,
    category: "AI in Design",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-025",
    question: "AI अपस्केलिंग (Upscaling) क्या करता है?",
    options: ["कम रेजोल्यूशन वाली इमेज या वीडियो की क्वालिटी और डिटेल बढ़ाना", "इमेज को क्रॉप करना", "फोटो को ब्लैक एंड व्हाइट करना", "फाइल को कंप्रेस करके खराब करना"],
    correct_option: 0,
    category: "AI in Design",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },

  // 26-45: Business, Marketing, Healthcare, Automation & Ethics
  {
    id: "q-026",
    question: "बिजनेस में AI ऑटोमेशन (Automation) का सबसे मुख्य फायदा क्या है?",
    options: ["दोहराए जाने वाले मैनुअल कार्यों को स्वचालित करके समय और लागत बचाना", "कर्मचारियों के कंप्यूटर बंद करना", "सिर्फ टैक्स बढ़ाना", "कागजी फाइलों का ढेर लगाना"],
    correct_option: 0,
    category: "AI in Business",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-027",
    question: "डिजिटल मार्केटिंग में AI का उपयोग किसमें सबसे प्रभावी है?",
    options: ["टारगेटेड विज्ञापन, पर्सनलाइज्ड कंटेंट और कस्टमर बिहेवियर एनालिसिस", "अखबार में पैम्फलेट बांटना", "सिर्फ ईमेल डिलीट करना", "दुकान का शटर बंद करना"],
    correct_option: 0,
    category: "AI in Marketing",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-028",
    question: "कस्टमर सपोर्ट में AI चैटबॉट्स का क्या महत्व है?",
    options: ["24x7 तत्काल प्रतिक्रिया और ग्राहकों के सवालों का त्वरित समाधान", "कॉल को डिस्कनेक्ट करना", "सिर्फ ऑफिस का पता बताना", "फोन की घंटी बंद करना"],
    correct_option: 0,
    category: "Conversational AI",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-029",
    question: "हेल्थकेयर (स्वास्थ्य सेवा) में AI का सबसे क्रांतिकारी उपयोग क्या है?",
    options: ["एक्स-रे/एमआरआई इमेज डायग्नोस्टिक्स और दवा खोज (Drug Discovery)", "हॉस्पिटल का बिल प्रिंट करना", "एम्बुलेंस का सायरन बजाना", "दवाइयों के पैकेट गिनना"],
    correct_option: 0,
    category: "AI in Healthcare",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-030",
    question: "एजुकेशन में AI ट्यूटरिंग सिस्टम क्या प्रदान करता है?",
    options: ["प्रत्येक विद्यार्थी की गति और समझ के अनुसार पर्सनलाइज्ड लर्निंग", "सभी को एक जैसी सजा देना", "किताबों की बिक्री बढ़ाना", "स्कूल की छुट्टी घोषित करना"],
    correct_option: 0,
    category: "AI in Education",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-031",
    question: "सेल्स और CRM में AI लीड स्कोरिंग का क्या अर्थ है?",
    options: ["डेटा विश्लेषण द्वारा सबसे संभावित ग्राहकों (High Intent Leads) की पहचान करना", "फोन नंबर डायल करना", "कागजी डायरी में नाम लिखना", "सारे ग्राहकों को ब्लॉक करना"],
    correct_option: 0,
    category: "AI in Sales",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-032",
    question: "ऑटोनॉमस व्हीकल्स (सेल्फ-ड्राइविंग कार) में किन AI तकनीकों का समन्वय होता है?",
    options: ["कंप्यूटर विजन, सेंसर फ्यूजन और डीप रीइन्फोर्समेंट लर्निंग", "केवल रेडियो रिसीवर", "कार का एसी कंट्रोलर", "सिर्फ हॉर्न का स्विच"],
    correct_option: 0,
    category: "Robotics",
    difficulty: "hard",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-033",
    question: "AI में 'Hallucination' (भ्रम) का क्या अर्थ है?",
    options: ["जब AI मॉडल पूरी तरह से गलत या मनगढ़ंत जानकारी को आत्मविश्वास से प्रस्तुत करे", "जब कंप्यूटर बंद हो जाए", "जब इंटरनेट की स्पीड कम हो", "जब मॉनिटर हिलने लगे"],
    correct_option: 0,
    category: "AI Ethics",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-034",
    question: "AI में डेटा प्राइवेसी और एथिक्स क्यों महत्वपूर्ण हैं?",
    options: ["उपयोगकर्ताओं के निजी डेटा की सुरक्षा और पक्षपात (Bias) को रोकने के लिए", "केवल सर्वर की बिजली बचाने के लिए", "सिर्फ फाइल्स का साइज बढ़ाने के लिए", "पासवर्ड को सार्वजनिक करने के लिए"],
    correct_option: 0,
    category: "AI Ethics",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-035",
    question: "RPA (Robotic Process Automation) का क्या काम है?",
    options: ["नियम-आधारित दोहराए जाने वाले डिजिटल कार्यों को ऑटोमेट करना", "लोहे के रोबोट बनाना", "कार का इंजन असेंबल करना", "बिल्डिंग बनाना"],
    correct_option: 0,
    category: "AI Automation",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },

  // 36-60: Careers, Freelancing & Practical Skills
  {
    id: "q-036",
    question: "फ्रीलांसिंग में AI टूल्स सीखने वाले युवा किस क्षेत्र में सेवाएं दे सकते हैं?",
    options: ["कंटेंट राइटिंग, ग्राफिक डिजाइन, वीडियो एडिटिंग और AI ऑटोमेशन", "सिर्फ ऑफलाइन कोरियर डिलीवरी", "टाइपराइटर रिपेयरिंग", "अखबार बांटना"],
    correct_option: 0,
    category: "Freelancing",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-037",
    question: "फ्रीलांसिंग या करियर में सफलता किस बात पर निर्भर करती है?",
    options: ["व्यावहारिक कौशल (Skills), मजबूत पोर्टफोलियो और निरंतर सीखने की लगन", "सिर्फ जादुई वादों पर", "बिना सीखे काम मिलने पर", "केवल भाग्य पर"],
    correct_option: 0,
    category: "Careers",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-038",
    question: "AI प्रॉम्प्ट इंजीनियर के रूप में करियर बनाने के लिए क्या आवश्यक है?",
    options: ["सटीक भाषा अभिव्यक्ति, क्रिटिकल थिंकिंग और मॉडल आर्किटेक्चर की समझ", "सिर्फ टाइपिंग स्पीड", "ड्राइंग की डिग्री", "सिर्फ गेम्स खेलना"],
    correct_option: 0,
    category: "Prompt Engineering",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-039",
    question: "AI के युग में एक पेशेवर (Professional) के लिए सबसे मूल्यवान कौशल क्या है?",
    options: ["AI टूल्स को अपने डोमेन में कुशलता से एकीकृत करने की क्षमता", "AI का विरोध करना", "कंप्यूटर बंद रखना", "केवल पुराने तरीकों पर अड़े रहना"],
    correct_option: 0,
    category: "Skills",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-040",
    question: "Upwork या Fiverr जैसे ग्लोबल प्लेटफॉर्म पर AI स्किल्स का क्या फायदा है?",
    options: ["अंतरराष्ट्रीय क्लाइंट्स के प्रोजेक्ट्स को तेज गति और उच्च क्वालिटी से पूरा करना", "सिर्फ प्रोफाइल फोटो बदलना", "फ्री में काम करना", "कंप्यूटर को फॉर्मेट करना"],
    correct_option: 0,
    category: "Freelancing",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },

  // 41-75: BMB Educom Grounded Learning & Practical Methodology
  {
    id: "q-041",
    question: "BMB Educom का AI सेमिनार किस मुख्य उद्देश्य से आयोजित किया जाता है?",
    options: ["छात्रों और पेशेवरों को भविष्य के AI टूल्स और करियर अवसरों से व्यावहारिक रूप से जोड़ना", "केवल किताबी थ्योरी सुनाना", "सिर्फ समय व्यतीत करना", "हार्डवेयर के पुर्जे बेचना"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: true,
    active: true
  },
  {
    id: "q-042",
    question: "BMB Educom में सीखने की पद्धति किस पर केंद्रित है?",
    options: ["प्रैक्टिकल हैंड्स-ऑन प्रोजेक्ट्स, इंडस्ट्री मेंटॉरशिप और रियल-वर्ल्ड टूल्स", "केवल रट्टा मार परीक्षा", "सिर्फ लेक्चर सुनना", "बिना प्रैक्टिकल के पढ़ाई"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: true,
    active: true
  },
  {
    id: "q-043",
    question: "BMB Educom के अनुसार AI किस तरह का सहायक टूल है?",
    options: ["मानव रचनात्मकता और कार्यक्षमता को कई गुना बढ़ाने वाला शक्तिशाली सहायक", "इंसानों की जगह लेने वाला रोबोट", "एक खतरनाक वायरस", "सिर्फ एक गेमिंग सॉफ्टवेयर"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: true,
    active: true
  },
  {
    id: "q-044",
    question: "BMB Educom का शुक्रवार का लाइव सेमिनार कब आयोजित होता है?",
    options: ["प्रत्येक शुक्रवार सुबह 11:00 बजे से शाम 4:00 बजे तक (IST)", "सोमवार की रात को", "महीने में केवल एक बार", "रविवार की सुबह 6 बजे"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: true,
    active: true
  },
  {
    id: "q-045",
    question: "BMB Educom के AI लर्निंग मॉड्यूल में किन-किन कौशलों का समन्वय है?",
    options: ["AI प्रॉम्प्टिंग, विजुअल डिजाइन, वीडियो क्रिएशन, कोडिंग असिस्टेंस और बिजनेस ऑटोमेशन", "केवल कीबोर्ड टाइपिंग", "सिर्फ एमएस पेंट", "सिर्फ फोटो कॉपी करना"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: true,
    active: true
  },
  {
    id: "q-046",
    question: "BMB AI सेमिनार क्विज में कुल कितने प्रश्न पूछे जाते हैं?",
    options: ["4 प्रश्न", "10 प्रश्न", "20 प्रश्न", "50 प्रश्न"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: true,
    active: true
  },
  {
    id: "q-047",
    question: "BMB AI क्विज को पूरा करने के लिए आधिकारिक सर्वर टाइमर कितना निर्धारित है?",
    options: ["2 मिनट (120 सेकंड)", "10 मिनट", "30 मिनट", "1 घंटा"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: true,
    active: true
  },
  {
    id: "q-048",
    question: "BMB Educom लीडरबोर्ड पर शीर्ष रैंकिंग किस आधार पर तय होती है?",
    options: ["उच्चतम स्कोर (Score) और सबसे तेज सर्वर-सत्यापित समय (Duration)", "केवल पहले रजिस्ट्रेशन करने पर", "प्रतिभागी के शहर के नाम पर", "रैंडम लकी ड्रॉ द्वारा"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: true,
    active: true
  },
  {
    id: "q-049",
    question: "BMB Educom में सर्टिफिकेशन और मेंटरशिप का क्या उद्देश्य है?",
    options: ["उद्योग-मानक कौशल सत्यापन और करियर मार्गदर्शन प्रदान करना", "केवल कागजी प्रमाण पत्र बांटना", "बिना कौशल के नौकरी का दावा करना", "सिर्फ फीस लेना"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: true,
    active: true
  },
  {
    id: "q-050",
    question: "AI सीखने के बाद एक छात्र का पहला व्यावहारिक कदम क्या होना चाहिए?",
    options: ["स्वयं के 3-5 लाइव प्रोजेक्ट्स बनाकर एक मजबूत डिजिटल पोर्टफोलियो तैयार करना", "सीखना बंद कर देना", "बिना सीखे नौकरी की मांग करना", "सोशल मीडिया पर केवल टाइम पास करना"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: true,
    active: true
  },

  // 51-105: Extended Depth across AI Technologies
  {
    id: "q-051",
    question: "AI में 'Fine-Tuning' का क्या मतलब है?",
    options: ["पहले से ट्रेंड मॉडल को किसी विशेष डोमेन या कार्य के लिए अतिरिक्त डेटा से अनुकूलित करना", "कंप्यूटर के वॉल्यूम को ट्यून करना", "रेडियो स्टेशन बदलना", "कीबोर्ड की ट्यूनिंग करना"],
    correct_option: 0,
    category: "Machine Learning",
    difficulty: "hard",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-052",
    question: "RAG (Retrieval-Augmented Generation) तकनीक का क्या लाभ है?",
    options: ["AI मॉडल को बाहरी निजी ज्ञानकोष (External Knowledge Base) से सटीक उत्तर देने में सक्षम बनाना", "कंप्यूटर की स्पीड दोगुनी करना", "सिर्फ फोटो एडिट करना", "वेबसाइट को रिफ्रेश करना"],
    correct_option: 0,
    category: "Generative AI",
    difficulty: "hard",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-053",
    question: "AI में 'Token' क्या होता है?",
    options: ["टेक्स्ट का सबसे छोटा अर्थपूर्ण खंड (शब्द या उप-शब्द) जिसे मॉडल प्रोसेस करता है", "मेट्रो का प्लास्टिक सिक्का", "कंप्यूटर की चाबी", "पासवर्ड की पर्ची"],
    correct_option: 0,
    category: "NLP",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-054",
    question: "क्वांटम कंप्यूटिंग और AI का भविष्य में क्या संबंध होगा?",
    options: ["अत्यंत जटिल समस्याओं और सिमुलेशन को सेकंडों में हल करने की अभूतपूर्व क्षमता", "दोनों का आपस में कोई संबंध नहीं होगा", "कंप्यूटर का वजन बढ़ जाएगा", "इंटरनेट बंद हो जाएगा"],
    correct_option: 0,
    category: "Future of AI",
    difficulty: "hard",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-055",
    question: "ऑडियो प्रोसेसिंग में AI डि-नॉइज़िंग (De-noising) क्या करती है?",
    options: ["बैकग्राउंड के अवांछित शोर को हटाकर आवाज को क्रिस्टल क्लीयर बनाना", "आवाज को म्यूट करना", "सिर्फ गाने का बास बढ़ाना", "हेडफोन को चार्ज करना"],
    correct_option: 0,
    category: "AI in Video Editing",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-056",
    question: "OCR (Optical Character Recognition) तकनीक क्या करती है?",
    options: ["तस्वीर या स्कैन किए गए दस्तावेज के टेक्स्ट को एडिटेबल डिजिटल टेक्स्ट में बदलना", "इमेज का प्रिंट निकालना", "स्क्रीन का कलर बदलना", "कंप्यूटर को लॉक करना"],
    correct_option: 0,
    category: "Computer Vision",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-057",
    question: "AI में 'Sentiment Analysis' का क्या उपयोग है?",
    options: ["ग्राहकों के रिव्यू और फीडबैक में छिपी सकारात्मक या नकारात्मक भावना का विश्लेषण करना", "मौसम का हाल बताना", "कंप्यूटर का तापमान नापना", "सिर्फ फोटो का रंग देखना"],
    correct_option: 0,
    category: "NLP",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-058",
    question: "AI वीडियो अवतार (AI Video Avatars) क्या होते हैं?",
    options: ["डिजिटल रूप से निर्मित वास्तविक जैसे बोलने वाले 3D/2D प्रेजेंटर", "कार्टून की पुरानी कॉमिक्स", "सिर्फ ऑडियो रिकॉर्डर", "कैमरा का स्टैंड"],
    correct_option: 0,
    category: "Generative AI",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-059",
    question: "AI में 'Overfitting' का क्या अर्थ है?",
    options: ["जब मॉडल ट्रेनिंग डेटा को जरूरत से ज्यादा रट ले और नए डेटा पर खराब प्रदर्शन करे", "जब कंप्यूटर में जगह खत्म हो जाए", "जब स्क्रीन पर इमेज बहुत बड़ी दिखे", "जब कीबोर्ड जाम हो जाए"],
    correct_option: 0,
    category: "Machine Learning",
    difficulty: "hard",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-060",
    question: "AI में 'Embedding' का क्या कार्य है?",
    options: ["टेक्स्ट, इमेज या डेटा को गणितीय वेक्टर्स (Mathematical Vectors) में बदलना", "वेबसाइट पर वीडियो चिपकाना", "फोटो फ्रेम में लगाना", "फाइल को जिप करना"],
    correct_option: 0,
    category: "Deep Learning",
    difficulty: "hard",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-061",
    question: "साइबर सिक्योरिटी में AI का क्या उपयोग है?",
    options: ["रीयल-टाइम में नए साइबर खतरों और मैलवेयर अटैक की पहचान व रोकथाम", "पासवर्ड को चुराना", "कंप्यूटर को धीमा करना", "इंटरनेट केबल काटना"],
    correct_option: 0,
    category: "AI in Business",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-062",
    question: "AI मॉडल के 'Temperature' पैरामीटर का क्या प्रभाव होता है?",
    options: ["आउटपुट में रचनात्मकता (Creativity) और विविधता (Randomness) का स्तर नियंत्रित करना", "कंप्यूटर का वास्तविक तापमान बढ़ाना", "मॉनिटर की रोशनी कम करना", "सिर्फ पंखे की स्पीड बढ़ाना"],
    correct_option: 0,
    category: "Generative AI",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-063",
    question: "BMB Educom के सेमिनार में AI टूल्स का व्यावहारिक प्रदर्शन क्यों किया जाता है?",
    options: ["ताकि प्रतिभागी वास्तविक दुनिया में इन टूल्स का उपयोग तुरंत सीख सकें", "केवल समय बिताने के लिए", "सिर्फ स्क्रीन दिखाने के लिए", "बिना किसी कारण के"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: true,
    active: true
  },
  {
    id: "q-064",
    question: "ई-कॉमर्स में AI रेकमेंडेशन इंजन (Recommendation Engine) क्या करता है?",
    options: ["ग्राहक की पसंद और पिछली खरीद के आधार पर पसंदीदा उत्पादों का सुझाव देना", "दुकान का किराया तय करना", "डिलीवरी ट्रक का पेट्रोल नापना", "सिर्फ बिल की रसीद फाड़ना"],
    correct_option: 0,
    category: "AI in Sales",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-065",
    question: "AI में 'Zero-Shot Learning' का क्या अर्थ है?",
    options: ["बिना किसी पूर्व उदाहरण (Example) के केवल विवरण के आधार पर सही वर्गीकरण करना", "शून्य नंबर लाना", "कंप्यूटर को शून्य पर सेट करना", "बिना बिजली के काम करना"],
    correct_option: 0,
    category: "Generative AI",
    difficulty: "hard",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-066",
    question: "AI एजेंट वर्कफ्लो में 'Multi-Agent Collaboration' का क्या लाभ है?",
    options: ["अलग-अलग विशेषज्ञ AI एजेंट्स मिलकर जटिल प्रोजेक्ट्स को स्वायत्त रूप से पूरा करते हैं", "कंप्यूटर की बैटरी जल्दी खत्म करना", "सिर्फ इंटरनेट पर ट्रैफिक बढ़ाना", "सॉफ्टवेयर क्रैश करना"],
    correct_option: 0,
    category: "AI Agents",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-067",
    question: "फ्रीलांसिंग में AI कंटेंट क्रिएटर के लिए क्या अनिवार्य है?",
    options: ["AI जनरेटेड कंटेंट की ह्यूमन एडिटिंग, फैक्ट-चेकिंग और ओरिजिनल टच", "कंटेंट को बिना देखे सीधे क्लाइंट को भेजना", "सिर्फ कॉपी पेस्ट करना", "गलत जानकारी फैलाना"],
    correct_option: 0,
    category: "Freelancing",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-068",
    question: "BMB Educom के AI लर्निंग पाथवे में सबसे पहला चरण क्या सिखाया जाता है?",
    options: ["AI की बुनियादी समझ, प्रॉम्प्टिंग तकनीक और सही टूल्स का चयन", "सीधे जटिल रोबोट बनाना", "केवल किताबें पढ़ना", "बिना सीखे एग्जाम देना"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: true,
    active: true
  },
  {
    id: "q-069",
    question: "AI में 'Context Window' क्या होती है?",
    options: ["वह अधिकतम टेक्स्ट या जानकारी जिसे मॉडल एक समय में याद रखकर प्रोसेस कर सकता है", "कंप्यूटर की खिड़की", "ब्राउज़र का नया टैब", "मॉनिटर का फ्रेम"],
    correct_option: 0,
    category: "Generative AI",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-070",
    question: "स्मार्ट एग्रीकल्चर (खेती) में AI ड्रोन और विजन सिस्टम क्या करते हैं?",
    options: ["फसल की बीमारियों की पहचान, मिट्टी की नमी और सटीक कीटनाशक छिड़काव", "सिर्फ खेत के ऊपर उड़ना", "पक्षियों को फोटो खींचना", "ट्रैक्टर का हॉर्न बजाना"],
    correct_option: 0,
    category: "Robotics",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-071",
    question: "AI में 'Chain of Thought (CoT)' प्रॉम्प्टिंग क्या होती है?",
    options: ["मॉडल को चरणबद्ध (Step-by-Step) तरीके से तार्किक सोच के साथ उत्तर देने के लिए प्रेरित करना", "सोने की चेन की फोटो बनाना", "लगातार टाइपिंग करना", "सिर्फ हां या ना में उत्तर मांगना"],
    correct_option: 0,
    category: "Prompt Engineering",
    difficulty: "hard",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-072",
    question: "BMB Educom में विद्यार्थियों के लिए प्रोजेक्ट मेंटरशिप क्यों दी जाती है?",
    options: ["ताकि विद्यार्थी प्रैक्टिकल गलतियों से सीखकर उद्योग के लिए तैयार (Job-Ready) हो सकें", "केवल औपचारिकता पूरी करने के लिए", "सिर्फ अटेंडेंस लगाने के लिए", "बिना प्रोजेक्ट के पास करने के लिए"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: true,
    active: true
  },
  {
    id: "q-073",
    question: "ऑडियो डबिंग में AI का सबसे आधुनिक उपयोग क्या है?",
    options: ["एक भाषा के वीडियो को मूल वक्ता की आवाज और लिप-सिंक के साथ अन्य भाषाओं में डब करना", "आवाज को म्यूट कर देना", "सिर्फ सबटाइटल हटाना", "वीडियो की स्पीड कम करना"],
    correct_option: 0,
    category: "AI in Video Editing",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-074",
    question: "AI मॉडल के 'Latency' का क्या अर्थ है?",
    options: ["इनपुट देने से लेकर आउटपुट प्राप्त होने तक का समय (रिस्पॉन्स टाइम)", "कंप्यूटर का वजन", "स्क्रीन का साइज", "इंटरनेट का मासिक खर्च"],
    correct_option: 0,
    category: "AI Basics",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-075",
    question: "BMB Educom का उद्देश्य छात्रों को किस प्रकार तैयार करना है?",
    options: ["सच्चे व्यावहारिक कौशल, निरंतर सीखने की मानसिकता और आत्मनिर्भर पेशेवर के रूप में", "केवल शॉर्टकट अपनाने वाले के रूप में", "किताबी रट्टामार के रूप में", "केवल परीक्षा पास करने वाले के रूप में"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: true,
    active: true
  },
  {
    id: "q-076",
    question: "ग्राफिक डिजाइन में AI वेक्टर जेनरेशन क्या करता है?",
    options: ["वेक्टर ग्राफिक्स (SVG) जनरेट करना जिन्हें बिना पिक्सल फटे किसी भी साइज में स्केल किया जा सके", "केवल फोटो डिलीट करना", "प्रिंटर का कलर बदलना", "मॉनिटर बंद करना"],
    correct_option: 0,
    category: "AI in Design",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-077",
    question: "AI में 'Diffusion Models' किस काम में सबसे प्रसिद्ध हैं?",
    options: ["शोर (Noise) से हाई-क्वालिटी इमेजेस और वीडियोज जनरेट करने में", "सिर्फ टेक्स्ट फाइल डिलीट करने में", "कंप्यूटर की बैटरी चार्ज करने में", "कीबोर्ड को साफ करने में"],
    correct_option: 0,
    category: "Generative AI",
    difficulty: "hard",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-078",
    question: "AI कोडिंग में यूनिट टेस्टिंग (Unit Testing) ऑटोमेशन से क्या लाभ होता है?",
    options: ["कोड में छिपे बग्स और एरर्स को तुरंत पकड़कर सॉफ्टवेयर की विश्वसनीयता बढ़ाना", "सॉफ्टवेयर को हैंग करना", "कीबोर्ड के कीज को लॉक करना", "इंटरनेट धीमा करना"],
    correct_option: 0,
    category: "AI in Coding",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-079",
    question: "BMB Educom के सेमिनार में AI टूल्स सीखने के बाद प्रतिभागियों को क्या प्राप्त होता है?",
    options: ["व्यावहारिक ज्ञान, लाइव क्विज में भाग लेने का अवसर और लीडरबोर्ड रैंकिंग", "सिर्फ एक पेपर ब्रोशर", "कोई जानकारी नहीं", "केवल एक खाली ईमेल"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: true,
    active: true
  },
  {
    id: "q-080",
    question: "AI में 'Few-Shot Prompting' का क्या मतलब है?",
    options: ["मॉडल को सही उत्तर देने के लिए 2-3 उदाहरण (Examples) प्रदान करना", "बंदूक की गोली चलाना", "सिर्फ एक शब्द लिखना", "बिना प्रॉम्प्ट के एंटर दबाना"],
    correct_option: 0,
    category: "Prompt Engineering",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-081",
    question: "AI चैटबॉट्स में 'Memory & State Management' क्यों आवश्यक है?",
    options: ["पिछली बातचीत के संदर्भ (Context) को याद रखकर सार्थक बातचीत जारी रखने के लिए", "हार्ड डिस्क को पूरा भरने के लिए", "सिर्फ यूजर का नाम भूलने के लिए", "कॉल काटने के लिए"],
    correct_option: 0,
    category: "Conversational AI",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-082",
    question: "AI वीडियो टूल्स में 'Motion Brush' फीचर का क्या काम है?",
    options: ["स्टैटिक इमेज के किसी चुनिंदा हिस्से में अपनी मर्जी से गति (Motion) देना", "दीवार पर पेंटिंग करना", "वीडियो को डिलीट करना", "कैमरा को हिलाना"],
    correct_option: 0,
    category: "AI in Video Editing",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-083",
    question: "फाइनेंस और बैंकिंग में AI का सबसे बड़ा उपयोग क्या है?",
    options: ["फ्रॉड डिटेक्शन (धोखाधड़ी की पहचान) और एल्गोरिद्मिक ट्रेडिंग", "बैंक की शाखा बंद करना", "सिक्के गिनना", "कागजी पासबुक प्रिंट करना"],
    correct_option: 0,
    category: "AI in Business",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-084",
    question: "BMB Educom का लीडरबोर्ड किन प्रतिभागियों के लिए विशेष है?",
    options: ["उसी शुक्रवार के सक्रिय सेमिनार में भाग लेने वाले सभी पंजीकृत प्रतिभागियों के लिए", "पूरे देश के सभी अज्ञात लोगों के लिए", "केवल पिछले साल के छात्रों के लिए", "केवल कॉलेज के शिक्षकों के लिए"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: true,
    active: true
  },
  {
    id: "q-085",
    question: "AI में 'Synthetic Data' क्या होता है?",
    options: ["एल्गोरिदम द्वारा कृत्रिम रूप से निर्मित सुरक्षित ट्रेनिंग डेटा", "नकली प्लास्टिक की वस्तु", "हैक किया गया डेटा", "कंप्यूटर की खराब फाइल"],
    correct_option: 0,
    category: "Machine Learning",
    difficulty: "hard",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-086",
    question: "AI 3D मॉडलिंग टूल्स (जैसे NeRF / Gaussian Splatting) क्या करते हैं?",
    options: ["2D फोटो संग्रह से रीयल-टाइम 3D वातावरण और मॉडल तैयार करना", "3D चश्मा बनाना", "सिर्फ स्क्रीन को 3D दिखाना", "प्रिंटर से कागज निकालना"],
    correct_option: 0,
    category: "AI in Animation",
    difficulty: "hard",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-087",
    question: "AI एजेंट्स में 'Function Calling' या 'Tool Calling' का क्या अर्थ है?",
    options: ["AI मॉडल का बाहरी APIs और डेटाबेस के साथ वास्तविक कार्य निष्पादित करना", "मोबाइल पर फोन लगाना", "कंप्यूटर में गाना बजाना", "सिर्फ एरर दिखाना"],
    correct_option: 0,
    category: "AI Agents",
    difficulty: "hard",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-088",
    question: "BMB Educom के अनुसार AI टूल्स सीखने के बाद कमाई की संभावना किस पर आधारित है?",
    options: ["मार्केट डिमांड, क्वालिटी पोर्टफोलियो, क्लाइंट डीलिंग और नियमित अभ्यास पर", "बिना किसी मेहनत के रातों-रात अमीर बनने पर", "केवल किसी सॉफ्टवेयर को डाउनलोड करने पर", "भाग्य के भरोसे रहने पर"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: true,
    active: true
  },
  {
    id: "q-089",
    question: "AI ट्रांसलेशन सिस्टम (Neural Machine Translation) का क्या लाभ है?",
    options: ["वाक्य के पूरे संदर्भ और मुहावरों को समझकर स्वाभाविक अनुवाद करना", "शब्द-दर-शब्द शाब्दिक गलत अनुवाद करना", "दूसरी भाषा को मिटाना", "सिर्फ डिक्शनरी खोलना"],
    correct_option: 0,
    category: "NLP",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-090",
    question: "AI में 'Transformer Architecture' की मुख्य नींव क्या है?",
    options: ["सेल्फ-अटेंशन मैकेनिज्म (Self-Attention Mechanism)", "बिजली का ट्रांसफार्मर", "मैकेनिकल गियर", "कंप्यूटर का फैन"],
    correct_option: 0,
    category: "Deep Learning",
    difficulty: "hard",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-091",
    question: "कंटेंट राइटिंग में AI टूल्स का सबसे अच्छा उपयोग कैसे किया जाना चाहिए?",
    options: ["आइडिया जनरेशन, रिसर्च आउटलाइन और ड्राफ्टिंग के बाद मानवीय संपादन", "बिना पढ़े सीधे पब्लिश करना", "दूसरे का नाम हटाना", "इंटरनेट से कॉपी पेस्ट करना"],
    correct_option: 0,
    category: "AI Skills",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-092",
    question: "BMB AI सेमिनार के दौरान 2 मिनट का टाइमर समाप्त होने पर क्या होता है?",
    options: ["सिस्टम ऑटो-सबमिट (Auto-Submit) करके उस समय तक चयनित उत्तरों का सर्वर स्कोर दर्ज कर लेता है", "क्विज हमेशा के लिए रद्द हो जाता है", "कंप्यूटर बंद हो जाता है", "शून्य नंबर मिलता है"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: true,
    active: true
  },
  {
    id: "q-093",
    question: "AI में 'Bias' (पूर्वाग्रह) कैसे उत्पन्न होता है?",
    options: ["जब ट्रेनिंग डेटा में किसी विशेष समूह या दृष्टिकोण का असंतुलित प्रतिनिधित्व हो", "जब कंप्यूटर पुराना हो जाए", "जब बिजली चली जाए", "जब कीबोर्ड खराब हो"],
    correct_option: 0,
    category: "AI Ethics",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-094",
    question: "मल्टीमॉडल AI (Multimodal AI) क्या होता है?",
    options: ["जो एक साथ टेक्स्ट, इमेज, ऑडियो और वीडियो को समझ और जनरेट कर सके", "जो सिर्फ एक ही भाषा समझे", "जो केवल गाने बजाए", "जो सिर्फ प्रिंट निकाले"],
    correct_option: 0,
    category: "Generative AI",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-095",
    question: "AI में 'Grounding' (ग्राउंडिंग) का क्या अर्थ है?",
    options: ["AI मॉडल के उत्तरों को सत्यापित और विश्वसनीय वास्तविक तथ्यों से जोड़ना", "कंप्यूटर को जमीन पर रखना", "अर्थिंग वायर लगाना", "मॉडल को बंद करना"],
    correct_option: 0,
    category: "AI Ethics",
    difficulty: "hard",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-096",
    question: "AI वीडियो जेनरेशन टूल्स में 'Camera Control' (Pan, Tilt, Zoom) का क्या उपयोग है?",
    options: ["जनरेटेड वीडियो में सिनेमैटिक कैमरा एंगल और मूवमेंट सेट करना", "मोबाइल का कैमरा ऑन करना", "स्क्रीन को घुमाना", "फोटो का साइज छोटा करना"],
    correct_option: 0,
    category: "AI in Video Editing",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-097",
    question: "BMB Educom का उद्देश्य विद्यार्थियों को किस प्रकार की शिक्षा देना है?",
    options: ["आधुनिक तकनीकों के साथ भविष्य की नौकरियों और उद्यमिता के लिए तैयार करने वाली शिक्षा", "केवल पुरानी किताबों की थ्योरी", "बिना किसी दिशा के पढ़ाई", "सिर्फ परीक्षा के अंक लाना"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: true,
    active: true
  },
  {
    id: "q-098",
    question: "AI में 'Reinforcement Learning from Human Feedback (RLHF)' क्यों प्रयोग होता है?",
    options: ["AI मॉडल के उत्तरों को मानव प्राथमिकताओं और सुरक्षा मानकों के अनुकूल बनाने के लिए", "कंप्यूटर को रीस्टार्ट करने के लिए", "सिर्फ यूजर का फीडबैक डिलीट करने के लिए", "स्क्रीन का कलर बदलने के लिए"],
    correct_option: 0,
    category: "Deep Learning",
    difficulty: "hard",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-099",
    question: "AI साउंड डिजाइन टूल्स किसमें मदद करते हैं?",
    options: ["टेक्स्ट विवरण से मूल बैकग्राउंड म्यूजिक, साउंड इफेक्ट्स (SFX) और ऑडियो ट्रैक्स बनाना", "हेडफोन ठीक करना", "रेडियो बजाना", "स्पीकर का वॉल्यूम कम करना"],
    correct_option: 0,
    category: "Generative AI",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-100",
    question: "BMB AI सेमिनार में सफल होने के लिए सबसे महत्वपूर्ण क्या है?",
    options: ["सीखने के सभी मॉड्यूल्स को ध्यानपूर्वक समझना और समय प्रबंधन के साथ सटीक उत्तर देना", "सिर्फ तुक्का लगाना", "क्विज को बीच में छोड़ देना", "दोस्त से पूछना"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: true,
    active: true
  },
  {
    id: "q-101",
    question: "AI आधारित 'Smart Search' सामान्य कीवर्ड सर्च से कैसे बेहतर है?",
    options: ["यह उपयोगकर्ता के प्रश्न के अर्थ और भाव (Semantic Meaning) को समझकर सटीक उत्तर देता है", "यह सिर्फ शब्दों को मैच करता है", "यह केवल पुरानी फाइल्स दिखाता है", "यह सर्च को धीमा करता है"],
    correct_option: 0,
    category: "AI Basics",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-102",
    question: "BMB Educom के AI लर्निंग में 'Hassle-Free Mobile Experience' का क्या अर्थ है?",
    options: ["हर मोबाइल स्क्रीन पर आसानी से चलने वाला सुपर-फास्ट और स्पष्ट इंटरफेस", "केवल लैपटॉप पर चलना", "सिर्फ वाईफाई पर काम करना", "धीमा लोड होना"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: true,
    active: true
  },
  {
    id: "q-103",
    question: "AI में 'Edge AI' का क्या मतलब है?",
    options: ["क्लाउड सर्वर के बजाय सीधे यूजर के मोबाइल या स्थानीय डिवाइस पर AI मॉडल को प्रोसेस करना", "कंप्यूटर के कोने पर AI लगाना", "इंटरनेट का तार काटना", "सिर्फ ऑफलाइन मोड में बंद होना"],
    correct_option: 0,
    category: "AI Basics",
    difficulty: "hard",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-104",
    question: "AI कोड रिव्यू टूल्स डेवलपर की कैसे मदद करते हैं?",
    options: ["सिक्योरिटी लूपहोल्स, मेमोरी लीक्स और कोडिंग स्टैंडर्ड्स की तुरंत जांच करना", "डेवलपर का कंप्यूटर लॉक करना", "कोड को बिना बताए डिलीट करना", "पासवर्ड सार्वजनिक करना"],
    correct_option: 0,
    category: "AI in Coding",
    difficulty: "medium",
    language: "hi",
    bmb_grounded: false,
    active: true
  },
  {
    id: "q-105",
    question: "BMB Educom के साथ जुड़ने का सबसे बड़ा फायदा क्या है?",
    options: ["सत्यापित ज्ञान, व्यावहारिक परियोजनाएं, मेंटरशिप और भविष्य के डिजिटल करियर का स्पष्ट रोडमैप", "केवल किताबी ज्ञान", "कोई दिशा नहीं", "अस्पष्ट वादे"],
    correct_option: 0,
    category: "BMB Learning",
    difficulty: "easy",
    language: "hi",
    bmb_grounded: true,
    active: true
  }
];
